name: Setup

inputs:
  node-version:
    default: lts/*
    required: false

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - uses: oven-sh/setup-bun@v1

    - name: Cache bun deps
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-node${{ inputs.node-version }}-bun-${{ hashFiles('**/bun.lockb') }}

    - name: Install deps
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install sharp
      shell: bash
      run: cd node_modules/sharp && bun install
